reset_major:
	python3 -m reset.reset_major

reset_dept:
	python3 -m reset.reset_department

reset_common:
	python3 -m reset.reset_common

init_dept:
	python3 -m initializer.initialize_department
	
init_common:
	python3 -m initializer.initialize_common

init_major:
	python3 -m initializer.initialize_major

update_major:
	python3 -m updater.update_major